# Generated by Django 3.0.6 on 2020-07-18 06:57

import uuid

from django.db import migrations, models
from main_app.models import User

def gen_uuid(apps, schema_editor):
        for row in User.objects.all():
            row.token = uuid.uuid4()
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200714_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
            preserve_default=True,
        ),

        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
