# Generated by Django 3.0.6 on 2020-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
