# Generated by Django 3.0.6 on 2020-07-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_group_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
