# Generated by Django 3.0.6 on 2020-08-04 12:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200725_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static', location='/Users/ivanderjmw/Projects/Heroku/teletamv1/staticfiles'), upload_to='media/'),
        ),
    ]
