# Generated by Django 3.0.6 on 2021-02-07 13:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200804_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static', location='/Users/ivanderjmw/Projects/teleteam-heroku/staticfiles'), upload_to='media/'),
        ),
    ]
